name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    env:
      venv_dir: .venv

    steps:
      - name: Checkout repo branch
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add executable paths to system PATH for the next steps
        run: |
          echo "${HOME}/.poetry/bin" >> ${GITHUB_PATH}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry -V

      - name: Install requirements
        run: |
          poetry install

      - name: Run lint
        run: |
          poetry run flake8 ./src

      - name: Run static type check
        run: |
          poetry run mypy ./src

      - name: Run tests
        run: |
          poetry run pytest